const verses = [
    "Create in me a pure heart, O God, and renew a steadfast spirit within me. - Psalm 51:10",
    "Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. - 2 Corinthians 4:16",
    "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. - Romans 12:2",
    "He gives strength to the weary and increases the power of the weak. - Isaiah 40:29",
    "I will give you a new heart and put a new spirit in you. - Ezekiel 36:26",
    "Serve wholeheartedly, as if you were serving the Lord, not people. - Ephesians 6:7",
    "Each of you should use whatever gift you have received to serve others. - 1 Peter 4:10",
    "For even the Son of Man did not come to be served, but to serve. - Mark 10:45",
    "Serve the Lord with gladness; come before him with joyful songs. - Psalm 100:2",
    "But grow in the grace and knowledge of our Lord and Savior Jesus Christ. - 2 Peter 3:18",
    "Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation. - 1 Peter 2:2",
    "I planted the seed, Apollos watered it, but God has been making it grow. - 1 Corinthians 3:6",
    "They will be like a tree planted by the water that sends out its roots by the stream. - Jeremiah 17:8",
    "The fear of the Lord is the beginning of wisdom; all who follow his precepts have good understanding. - Psalm 111:10",
    "Get wisdom, get understanding; do not forget my words or turn away from them. - Proverbs 4:5",
    "If any of you lacks wisdom, you should ask God, who gives generously to all. - James 1:5",
    "Be very careful, then, how you live—not as unwise but as wise. - Ephesians 5:15",
    "The wise in heart accept commands, but a chattering fool comes to ruin. - Proverbs 10:8",
    "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
    "In you, Lord my God, I put my trust. - Psalm 25:1",
    "Blessed is the one who trusts in the Lord, whose confidence is in him. - Jeremiah 17:7",
    "When I am afraid, I put my trust in you. - Psalm 56:3",
    "Be still before the Lord and wait patiently for him. - Psalm 37:7",
    "The Lord is good to those whose hope is in him, to the one who seeks him. - Lamentations 3:25",
    "Be patient, then, brothers and sisters, until the Lord's coming. - James 5:7",
    "Better a patient person than a warrior, one with self-control than one who takes a city. - Proverbs 16:32",
    "Wait for the Lord; be strong and take heart and wait for the Lord. - Psalm 27:14",
    "Be kind and compassionate to one another, forgiving each other. - Ephesians 4:32",
    "Whoever is kind to the poor lends to the Lord. - Proverbs 19:17",
    "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness. - Colossians 3:12",
    "A kind word turns away wrath, but a harsh word stirs up anger. - Proverbs 15:1",
    "Be strong and courageous. Do not be afraid; do not be discouraged. - Joshua 1:9",
    "The Lord is my light and my salvation—whom shall I fear? - Psalm 27:1",
    "Even though I walk through the darkest valley, I will fear no evil, for you are with me. - Psalm 23:4",
    "For the Spirit God gave us does not make us timid, but gives us power. - 2 Timothy 1:7",
    "Humble yourselves before the Lord, and he will lift you up. - James 4:10",
    "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves. - Philippians 2:3",
    "When pride comes, then comes disgrace, but with humility comes wisdom. - Proverbs 11:2",
    "For all those who exalt themselves will be humbled, and those who humble themselves will be exalted. - Luke 14:11",
    "Before a downfall the heart is haughty, but humility comes before honor. - Proverbs 18:12",
    "The light shines in the darkness, and the darkness has not overcome it. - John 1:5",
    "You are the light of the world. A town built on a hill cannot be hidden. - Matthew 5:14",
    "For God, who said, 'Let light shine out of darkness,' made his light shine in our hearts. - 2 Corinthians 4:6",
    "Your word is a lamp for my feet, a light on my path. - Psalm 119:105"
];

export default verses;